X(fabs, fabsl, 1, (x[0]))
X(fmod, fmodl, 2, (x[0], x[1]))
X(remainder, remainderl, 2, (x[0], x[1]))
X(fma, fmal, 3, (x[0], x[1], x[2]))
X(fmax, fmaxl, 2, (x[0], x[1]))
X(fmin, fminl, 2, (x[0], x[1]))
X(fdim, fdiml, 2, (x[0], x[1]))
X(exp, expl, 1, (x[0]))
X(exp2, exp2l, 1, (x[0]))
X(expm1, expm1l, 1, (x[0]))
X(log, logl, 1, (x[0]))
X(log10, log10l, 1, (x[0]))
X(log2, log2l, 1, (x[0]))
X(log1p, log1pl, 1, (x[0]))
X(pow, powl, 2, (x[0], x[1]))
X(sqrt, sqrtl, 1, (x[0]))
X(cbrt, cbrtl, 1, (x[0]))
X(hypot, hypotl, 2, (x[0], x[1]))
X(sin, sinl, 1, (x[0]))
X(cos, cosl, 1, (x[0]))
X(tan, tanl, 1, (x[0]))
X(asin, asinl, 1, (x[0]))
X(acos, acosl, 1, (x[0]))
X(atan, atanl, 1, (x[0]))
X(atan2, atan2l, 2, (x[0], x[1]))
X(sinh, sinhl, 1, (x[0]))
X(cosh, coshl, 1, (x[0]))
X(tanh, tanhl, 1, (x[0]))
X(asinh, asinhl, 1, (x[0]))
X(acosh, acoshl, 1, (x[0]))
X(atanh, atanhl, 1, (x[0]))
X(erf, erfl, 1, (x[0]))
X(erfc, erfcl, 1, (x[0]))
X(tgamma, tgammal, 1, (x[0]))
X(lgamma, lgammal, 1, (x[0]))
X(ceil, ceill, 1, (x[0]))
X(floor, floorl, 1, (x[0]))
X(trunc, truncl, 1, (x[0]))
X(nearbyint, nearbyintl, 1, (x[0]))
X(copysign, copysignl, 2, (x[0], x[1]))
#undef X

